version: '3'
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    tty:
      true
    volumes:
      - ./server:/go/app